[package]
name = "read_csv"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.45.1", features = ["rows", "lazy", "csv", "ipc"] }
calamine = "0.26.1"

[features]
write_output = ["polars/ipc", "polars/parquet"]
default = ["write_output"]
