[package]
name = "read_csv"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.44.2", features = ["lazy", "csv", "ipc"] }

[features]
write_output = ["polars/ipc", "polars/parquet"]
default = ["write_output"]
